# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=32, unique=True)),
                ('ctime', models.DateTimeField(auto_now_add=True, null=True)),
                ('uptime', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.CharField(default='aaa', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='test',
            field=models.EmailField(error_messages={'invalid': '请输入密码'}, max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_type_id',
            field=models.IntegerField(choices=[(1, '超级用户'), (2, '普通用户'), (3, '普普通用户')], default=1),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(help_text='pwd', max_length=60),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(blank=True, max_length=32, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.UserGroup'),
        ),
    ]
